# Generated by Django 5.2.5 on 2025-08-22 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_alter_topping_options_alter_topping_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topping',
            old_name='topic',
            new_name='pizza',
        ),
    ]
