# Generated by Django 5.2.5 on 2025-08-22 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_rename_topic_topping_pizza'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='text',
            new_name='name',
        ),
    ]
